# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "action_items", :force => true do |t|
    t.column "description",  :string,   :default => "",    :null => false
    t.column "list_item_id", :integer,                     :null => false
    t.column "order",        :integer,                     :null => false
    t.column "level",        :integer,                     :null => false
    t.column "remind_at",    :datetime
    t.column "done",         :boolean,  :default => false, :null => false
    t.column "created_at",   :datetime,                    :null => false
    t.column "updated_at",   :datetime,                    :null => false
  end

  create_table "list_items", :force => true do |t|
    t.column "description", :string,   :default => "",    :null => false
    t.column "user_id",     :integer,                     :null => false
    t.column "list_id",     :integer,                     :null => false
    t.column "remind_at",   :datetime
    t.column "done",        :boolean,  :default => false, :null => false
    t.column "created_at",  :datetime,                    :null => false
    t.column "updated_at",  :datetime,                    :null => false
  end

  create_table "lists", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",      :string,   :default => "", :null => false
    t.column "password",   :string,   :default => "", :null => false
    t.column "email",      :string,   :default => "", :null => false
    t.column "created_at", :datetime,                 :null => false
    t.column "updated_at", :datetime,                 :null => false
  end

end
